package: zipline
user: quantopian

platform:
  - linux-64
engine:
  - python=2.7
  - python=3.4

install:
  - conda config --add channels quantopian
  - conda config --set always_yes true
  - source deactivate
  # conda-build built from https://github.com/conda/conda-build/pull/717
  # (conda-build can only be installed in root env.)
  - conda install conda-build=1.10alpha.0
  - source activate /home/anaconda/env

before_script:
  - python -V

script:
  - conda build conda/zipline/

iotimeout: 600

build_targets: conda
